# Generated by Django 3.2.3 on 2021-07-26 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, unique=True)),
                ('artist', models.CharField(max_length=120)),
                ('genre', models.CharField(choices=[('HipHop', 'HipHop'), ('Jazz', 'Jazz'), ('Classical', 'Classical'), ('Dance', 'Dance'), ('Acoustic', 'Acoustic')], max_length=50)),
            ],
        ),
    ]
